---
- include_vars: secrets.yml

- name: configure wifi for home network
  blockinfile:
    path: /etc/wpa_supplicant/wpa_supplicant.conf
    block: |
      network={
          ssid="{{ wifi_name }}"
          psk="{{ wifi_password }}"
      }
